name: Dependabot Auto Approve & Merge
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Approve & Auto-Merge PR
        run: |
          gh pr review --approve "${PR_URL}"
          gh pr merge --auto --squash "${PR_URL}"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
